### PR TITLE
Added Undo/Redo and help buttons

### LINKED ISSUE #7: Undo/redo
Would be kinda neat - not an essential feature tho.

### LINKED ISSUE #8: Add help button
* Small `?` button on the page somewhere - perhaps in the footer?
* Should either link to or display a small help window, which explains how to use the editor.

### PR DESCRIPTION
**Pull request by BrainStone**
- Added undo and redo buttons + functionality (closes #7)
- Added help button (no text yet) (closes #8)

### CODE REVIEW

**Comment by Foorack** [comment]
When editing, if delete 1 node after importing and then undo everything is deleted. It works if I take 2 actions and only undo 1.
How to replicate:

1. Open (for example) a group.
2. Delete a permission node.
3. Undo. Everything is now deleted.

**Comment by Foorack** [comment]
Also, if you have a group with many nodes, for example 100 nodes, then the help box is displayed extremely far down. I guess it uses the page height, better would be to use window height when calculating position.

**Comment by lucko** [comment]
@BrainStone what's the status of this

**Comment by BrainStone** [comment]
Should be ready to go now!

**Comment by BrainStone** [comment]
Conflicts are easily resolved by adding everything

**Comment by lucko** [comment]
Can you merge again please

**Pull request merged**
